# Generated by Django 4.1.4 on 2022-12-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('object_name', models.CharField(max_length=50, verbose_name='Наименование объекта')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cоздана')),
            ],
            options={
                'verbose_name': 'Контактная форма',
                'verbose_name_plural': 'Контактные формы',
                'ordering': ['-created'],
            },
        ),
    ]
