# Generated by Django 4.1.4 on 2022-12-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_contact_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='field1',
            field=models.CharField(blank=True, max_length=255, verbose_name='field1'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='field2',
            field=models.CharField(blank=True, max_length=255, verbose_name='field2'),
        ),
    ]
